# from enum import IntEnum
from enum import Enum
class MessType(Enum):
   REQUEST_ROLE = 1 ## -----
   REQUEST_SIGN_UP = 2 # ---
   REQUEST_SIGN_IN = 3 # ----
   IS_NEW_QUIZ = 4 ##
   SEND_NEW_QUIZ = 5 ##
   RESPONSE_QUIZZES = 6 
   SEND_QUIZ_CHOICE = 7 ##
   SEND_PIN = 8
   SEND_NO_PLAYER = 9
   REQUEST_START_GAME = 10 ##
   RESPONSE_START_GAME = 11
   REQUEST_NEXT_QUESTION = 12 ##
   RESPONSE_NEXT_QUESTION = 13
   HOST_RESULT = 14
   SET_NICKNAME = 15 ## -----
   IS_VALID_NICKNAME = 16
   REQUEST_ROOM_PIN = 17 ##
   IS_VALID_ROOM_PIN = 18
   SEND_ANSWER = 19 ##
   PLAYER_RESULT = 20
   CONFIRM = 21
   END_GAME = 22
   CLOSE = 23
